version: "3"
services:
  webpdl2ork:
    # For pre-built GitHub image:
    image: ghcr.io/pd-l2ork/pd-l2ork:latest
    # For local image:
    # build:
    #   context: .
    #   dockerfile: webpdl2ork.Dockerfile
    environment:
      - PORT=80
      - PATCH_PATH=public/patches
      - VIRTUAL_HOST=l2ork.bukvic.net # Sets the domain name being used for pd-l2ork
    volumes:
      # The path before the ":" is where webpdl2ork will read patches from. 
      - ./emscripten/projects/WebPdL2Ork/public:/WebPdL2Ork/public/patches:ro
    restart: unless-stopped
    container_name: webpdl2ork
  nginx:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      # For HTTPS (requires SSL certificates):
      - "3000:443"
      # For HTTP (no additional requirements):
      # - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./logs:/var/log/nginx
    restart: unless-stopped
    container_name: nginx-proxy
    environment:
      - LOG_FORMAT=$$remote_addr - $$remote_user [$$time_local] "$$request" $$status $$body_bytes_sent "$$http_referer" "$$http_user_agent" $$host $$request_time $$upstream_cache_status
